export { default as HeroImg01 } from "../../assets/HeroImg01.png";
export { default as HeroImg02 } from "../../assets/hero-img-02.png";
export { default as HeroImg03 } from "../../assets/hero-img-03.png";
export { default as HeroImg04 } from "../../assets/hero-img-04.png";
export { default as HeroImg05 } from "../../assets/hero-img-05.png";
export { default as HeroImg06 } from "../../assets/hero-img-06.png";
export { default as HeroImg07 } from "../../assets/hero-img-07.png";
export { default as HeroImg08 } from "../../assets/hero-img-08.png";
export { default as HeroImg09 } from "../../assets/hero-img-09.png";
